### ISSUE TITLE
Getting Started | Netlify Section | npm run generate command fails

### ISSUE THREAD

**Issue by mtrueblood** [storyblok/nuxtdoc#4]
I'm following the getting started guide (https://nuxtdoc.js.org/v1/guide/getting-started) and all is well up to the Netlify - 'npm run generate' section. This command fails. Below is my terminal output.

node: 8.11.1
npm: 5.6.0

![image](https://user-images.githubusercontent.com/7134168/39874237-4224f25a-543b-11e8-82ef-1aed744fd428.png)

**Comment by mtrueblood** [comment]
Yep. Sorry. Here is the text from the terminal output:

                                                 Asset     Size  Chunks                    Chunk Names
               layouts_default.93dd8b9ec5e655e6bb14.js   400 kB       0  [emitted]  [big]  layouts_default
pages__version__category_index.786e226172a01d81a7f8.js   326 kB       1  [emitted]  [big]  pages__version__category_index
 pages__version__category__doc.ceae4aca19654f737e36.js   325 kB       2  [emitted]  [big]  pages__version__category__doc
                   pages_index.b55fa7aec2b5a24c1ec5.js   323 kB       3  [emitted]  [big]  pages_index
           pages__version_menu.df6129d74bb4ead50f28.js  1.52 kB       4  [emitted]         pages__version_menu
                        vendor.89aef18c35d27fb3a451.js   205 kB       5  [emitted]         vendor
                           app.3cfb422008eae1e3e232.js  40.1 kB       6  [emitted]         app
                      manifest.7fa467238b5289f54138.js  1.64 kB       7  [emitted]         manifest
                                              LICENSES  1.38 kB          [emitted]
 + 3 hidden assets

WARNING in asset size limit: The following asset(s) exceed the recommended size limit (300 kB).
This can impact web performance.
Assets:
  layouts_default.93dd8b9ec5e655e6bb14.js (400 kB)
  pages__version__category_index.786e226172a01d81a7f8.js (326 kB)
  pages__version__category__doc.ceae4aca19654f737e36.js (325 kB)
  pages_index.b55fa7aec2b5a24c1ec5.js (323 kB)
Hash: 6dd67f467c76e4d98dee
Version: webpack 3.11.0
Time: 1031ms
             Asset    Size  Chunks             Chunk Names
server-bundle.json  207 kB          [emitted]
  nuxt: Call generate:distRemoved hooks (1) +0ms
  nuxt:generate Destination folder cleaned +28s
  nuxt: Call generate:distCopied hooks (1) +63ms
  nuxt:generate Static & build files copied +63ms
  nuxt:render Rendering url / +0ms
  nuxt:render Rendering url v1/menu +99ms
  nuxt:render Rendering url /v1 +5ms
  nuxt:render Rendering url /v1/your-category +4ms
  nuxt: Call generate:page hooks (1) +3s
  nuxt:generate Generate file: v1\menu\index.html +3s
  nuxt: Call generate:page hooks (1) +564ms
  nuxt:generate Generate file: \v1\index.html +564ms
  nuxt: Call generate:page hooks (1) +70ms
  nuxt:generate Generate file: \v1\your-category\index.html +71ms
  nuxt:render Rendering url / +3s

 ERROR

  Error: Request failed with status code 404

  - createError.js:16 createError
    [nuxtdoc]/[axios]/lib/core/createError.js:16:15

  - settle.js:18 settle
    [nuxtdoc]/[axios]/lib/core/settle.js:18:12

  - http.js:192 IncomingMessage.handleStreamEnd
    [nuxtdoc]/[axios]/lib/adapters/http.js:192:11

  - events.js:111 emitNone
    events.js:111:20

  - events.js:208 IncomingMessage.emit
    events.js:208:7

  - _stream_readable.js:1064 endReadableNT
    _stream_readable.js:1064:12

  - next_tick.js:138 _combinedTickCallback
    internal/process/next_tick.js:138:11

  - next_tick.js:180 process._tickCallback
    internal/process/next_tick.js:180:9


  nuxt: Call generate:done hooks (1) +229ms
  nuxt:generate HTML Files generated in 31.7s +229ms

 Generate errors summary:

 ROUTE  /

  Error: Request failed with status code 404

  - createError.js:16 createError
    [nuxtdoc]/[axios]/lib/core/createError.js:16:15

  - settle.js:18 settle
    [nuxtdoc]/[axios]/lib/core/settle.js:18:12

  - http.js:192 IncomingMessage.handleStreamEnd
    [nuxtdoc]/[axios]/lib/adapters/http.js:192:11

  - events.js:111 emitNone
    events.js:111:20

  - events.js:208 IncomingMessage.emit
    events.js:208:7

  - _stream_readable.js:1064 endReadableNT
    _stream_readable.js:1064:12

  - next_tick.js:138 _combinedTickCallback
    internal/process/next_tick.js:138:11

  - next_tick.js:180 process._tickCallback
    internal/process/next_tick.js:180:9


  nuxt:generate Generate done +86ms
Error: Request failed with status code 404
    at createError (C:\Users\matt\Sites\new-digityll\nuxtdoc\node_modules\axios\lib\core\createError.js:16:15)
    at settle (C:\Users\matt\Sites\new-digityll\nuxtdoc\node_modules\axios\lib\core\settle.js:18:12)
    at IncomingMessage.handleStreamEnd (C:\Users\matt\Sites\new-digityll\nuxtdoc\node_modules\axios\lib\adapters\http.js:192:11)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nuxtdoc@1.0.0 generate: `nuxt generate`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nuxtdoc@1.0.0 generate script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\matt\AppData\Roaming\npm-cache\_logs\2018-05-10T14_08_59_604Z-debug.log

**Comment by DominikAngerer** [comment]
Hey @mtrueblood the `nuxt generate` part uses the published version of your content - it looks like you've not yet published those content entries - therefore you were not able to load it (resulting in 404). Can you try to publish content entries and run the script again?

**Comment by mtrueblood** [comment]
Thanks @DominikAngerer. It works now that I have published content. I didn't realize this was a needed step as it wasn't mentioned in the getting started guide. I also had to update the site_id in the .netlify file.

**Comment by DominikAngerer** [comment]
Thanks for the feedback. I'll update the getting started guide - the published content requirement was added later. Sorry to have you get hit by that issue. I'll update the guide accordingly.
