### ISSUE TITLE
Corresponding Storyblok Content

### ISSUE THREAD

**Issue by rahalio** [storyblok/nuxtdoc#5]
This is very useful, it would be great to include to the corresponding Storyblok Components and Content schemas etc...

Screen shots perhaps in the ReadMe file

Thx

**Comment by DominikAngerer** [comment]
Hey there!

Following the Getting Started Guide you will end up with the Content and Component Structure. https://nuxtdoc.js.org/v1/guide/getting-started/

You can also find the Seed Script used in the Getting Started Guide here: https://github.com/storyblok/nuxtdoc/blob/master/seed.js and the component structure here: https://github.com/storyblok/nuxtdoc/blob/master/seed.components.json
